CC = mpicc
F77 = mpif77
CFLAGS = -O3 -Wall
LDFLAGS = -O3
PLAT = LINUX

INCBLAS = -I./include
INCTOOLS = -I./tools

LIBSCALAPACK = -L/MY/PATH/ -lscalapack
LIBBLAS = -L/MY/PATH/ -lrefblas
LIBLAPACK = -L/MY/PATH/ -ltmg -lreflapack
SCALAPACK = $(LIBSCALAPACK) $(LIBLAPACK) $(LIBBLAS) 

